apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
  labels:
    app.kubernetes.io/name: $NAME
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: $NAME
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $NAME
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: $NAME
        image: {{ printf "%s%s:%s" (ternary (printf "%s.dkr.ecr.%s.amazonaws.com/" .Values.accountId .Values.region) "localhost:5001/" (eq .Values.environment "aws")) "$NAME" .Values.containers.$NAME.tag }}
      ports:
        - containerPort: 9000
        - containerPort: 42625
      volumeMounts:
        - name: $NAME-data
          mountPath: /data
      env:
        - name: ENV_VAR
          value: {{ .Values.config.fixme }}
      volumes:
      - name: $NAME-data
        persistentVolumeClaim:
          claimName: $NAME-pvc
