{{- if eq $.Values.environment "local" }}
{{- $${p}name := "$NAME-pv" }}
{{- $${p}storage := ternary "10Gi" "500Gi" (eq .Values.environment "local") }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $${p}name }}
spec:
    capacity:
        storage: {{ $${p}storage }}
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ""
    hostPath:
      path: "/{{ $${p}name }}"
{{- end }}

