{{- $${p}name := "$NAME-service" }}
{{- $${p}selector := "$NAME" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $${p}name }}
  labels:
    app.kubernetes.io/instance: trieve
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ $${p}name }}
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: trieve-0.1.0
    meta.helm.sh/release-name: trieve
    meta.helm.sh/release-namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: $NAME
    - port: 42625
      targetPort: 42625
      protocol: TCP
      name: $NAME-secondary
  selector:
    app.kubernetes.io/name: {{ $${p}selector }}
    app.kubernetes.io/instance: trieve
