apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: analytics
        image: {{ (printf "%s%s:%s" (ternary "trieve/" "localhost:5001/" (ne .Values.environment "local")) "analytics-site" .Values.containers.analytics.tag) }}
        ports:
          - containerPort: 80
        env:
          - name: VITE_API_HOST
            value: {{ .Values.config.vite.apiHost }}
          - name: VITE_DASHBOARD_URL
            value: {{ $.Values.config.vite.dashboardUrl }}
