{{- range $index, $service := .Values.embeddings }}
{{- $revision := (get $service "revision") }}
{{- $model := (get $service "model") }}
{{- $name := (get $service "name") }}
{{- $args := (get $service "args") }}
{{- if ne $index 0 }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-{{ $name }}
  labels:
    app.kubernetes.io/name: embedding-{{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: embedding-{{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: embedding-{{ $name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      {{- if eq $.Values.environment "gcloud" }}
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      {{- end }}
      containers:
        - name: embedding-{{ $name }}
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
          image: {{ ternary "ghcr.io/huggingface/text-embeddings-inference:89-1.2" "ghcr.io/huggingface/text-embeddings-inference:cpu-1.2" $.Values.useGpu }}
          args: 
            {{ (concat (list "--model-id" $model "--revision" $revision) $args) | toJson }}
          ports:
            - containerPort: 80
{{- if $.Values.useGpu }}
          resources:
            limits:
              nvidia.com/gpu: 1
{{- end }}
{{- end }}
