{{- $selector := "tika" }}
kind: Service
apiVersion: v1
metadata:
  name: tika
  labels:
    app.kubernetes.io/instance: trieve
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tika
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: trieve-0.1.0
    meta.helm.sh/release-name: trieve
    meta.helm.sh/release-namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: tika
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
