apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tika
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tika
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: tika
        image: {{ printf "%s%s:%s" "apache/" "tika" .Values.containers.tika.tag }}
        ports:
          - containerPort: 9998
