name: analytics test suite

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "frontends/analytics/**"
      - "frontends/shared/**"
      - "frontends/config/**"

jobs:
  build-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: frontends
        run: yarn --frozen-lockfile
      - name: Running lint
        working-directory: frontends
        run: yarn build --filter analytics
  eslint:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: frontends
        run: yarn --frozen-lockfile
      - name: Running lint
        working-directory: frontends
        run: yarn lint:CI --filter analytics
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./frontends/analytics/eslint_report.json"
