name: Create Frontend Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
    - 'frontends/dashboard/**'
    - 'frontends/search/**'
    - 'frontends/chat/**'
    - 'frontends/analytics-site/**'
    - 'frontends/shared/**'
    - 'frontends/config/**'
    - '.github/workflows/**'

jobs:
  build_chat:
    name: Push Chat Image
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/chat
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=trieve/buildcache:chat
          cache-to: type=registry,ref=trieve/buildcache:chat,mode=max
          file: frontends/chat/Dockerfile
          context: ./frontends
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_search:
    name: Push Search Image
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/search
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=trieve/buildcache:search
          cache-to: type=registry,ref=trieve/buildcache:search,mode=max
          file: frontends/search/Dockerfile
          context: ./frontends
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_dashboard:
    name: Push Dashboard Image
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/dashboard
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=trieve/buildcache:dashboard
          cache-to: type=registry,ref=trieve/buildcache:dashboard,mode=max
          file: frontends/dashboard/Dockerfile
          context: ./frontends
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_analytics_site:
    name: Push Analytics Image
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            trieve/analytics-site
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # platforms: linux/amd64,linux/arm64
          file: frontends/analytics/Dockerfile
          context: ./frontends
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
